DEBUG: true
APP_NAME: core
COCKROACHDB_HOST: localhost
COCKROACHDB_PORT: 26257
COCKROACHDB_USERNAME: roach
COCKROACHDB_DATABASE: reference
COCKROACHDB_TLS_ENABLE: false
COCKROACHDB_TLS_SKIP_VERIFY: true
COCKROACHDB_MAX_CONN: 100
COCKROACHDB_MAX_CONN_IDLE_TIME: 5
APP_ADDRESS_PORT: :8080
