version: '3.5'

services:
  cockroachdb:
    container_name: cockroachdb
    image: cockroachdb/cockroach:v23.1.1
    ports:
      - 26257:26257
      - 8080:8080
    command: start-single-node --insecure
    volumes:
      - "${PWD}/cockroach-data/crdb:/cockroach/cockroach-data"
    hostname: cockroachdb
    networks:
      - cockroachdb

networks:
  cockroachdb:
