package userids

const (
	_package             = "userids"
	_entityName          = "User ID"
	_entityNamePlural    = "User IDs"
	_fields              = "user_id, credential_id, physique_id, liveliness_id, social_id, status"
	_table               = "core.userids"
	_createSymbol        = "CREATE"
	_updateSymbol        = "UPDATE"
	_contactTableName    = "core.users_contacts"
	_contactFields       = "id, type, value, status"
	_userContactFields   = "user_id, label, contact_id, main_contact, status"
	_userIDsFields       = "user_id, credential_id, physique_id, liveliness_id, social_id, status"
	defaultUUID          = "00000000-00000000-00000000-00000000"
	_contactPackage      = "usercontacts"
	_contactTable        = "core.users_contacts"
	_userContactsFields  = "user_id, label, contact_id, main_contact, status"
	_addressTableName    = "core.users_addresses"
	_incomeTableName     = "core.users_incomes"
	_userIncomeFields    = "user_id, label, income_id, status"
	_contactAddSymbol    = "ADD_CONTACTS"
	_contactUpdateSymbol = "UPDATE_CONTACTS"
	_contactUpsertSymbol = "UPSERT_CONTACTS"
	_incomeAddSymbol     = "ADD_INCOMES"
	_incomeUpdateSymbol  = "UPDATE_INCOMES"
	_incomeUpsertSymbol  = "UPSERT_INCOMES"
	_addressPackage      = "useraddresses"
	_incomePackage       = "userincomes"
	_userAddressFields   = "user_id, label, address_id, main_address, ownership_status,status"
)
